# Generated by Django 2.0.7 on 2019-05-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_blogcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='comment',
            field=models.TextField(max_length=10000),
        ),
    ]
